# Generated by Django 3.2 on 2021-06-18 13:45

import MKsystemApp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='ユーザID')),
                ('deposit_value', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=100, null=True, verbose_name='資産')),
                ('deposit_date', models.DateTimeField(null=True, verbose_name='変更日時')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='ユーザID')),
                ('date', models.DateTimeField(null=True, verbose_name='日時')),
                ('value', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='')),
                ('status', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='状況')),
                ('status_date', models.DateTimeField(null=True, verbose_name='変更日時')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('rank', models.IntegerField(blank=True, choices=[(1, '運営'), (2, '特別会員'), (3, '一般会員')], default=0, null=True, verbose_name='会員ランク')),
                ('family_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('zip', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='フォーマットが不正です。', regex='\\d{3}\\-?\\d{4}')], verbose_name='郵便番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='フォーマットが不正です。', regex='(^0\\d{9,10}$)|(^0\\d{2,3}-\\d{1,4}-\\d{4}$)')], verbose_name='電話番号')),
                ('btc_address', models.CharField(default='', max_length=34, validators=[django.core.validators.RegexValidator(message='フォーマットが不正です。', regex='^[0-9a-zA-Z]+$')], verbose_name='ビットコインアドレス')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='管理者')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='利用開始')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', MKsystemApp.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='資産')),
                ('asset_date', models.DateField(null=True, verbose_name='資産更新日付')),
                ('is_accept', models.BooleanField(default=False, verbose_name='承諾')),
                ('accept_date', models.DateField(null=True, verbose_name='承諾日付')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
