# Generated by Django 3.2 on 2021-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0002_alter_asset_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='accept_date',
            field=models.DateTimeField(null=True, verbose_name='承諾日付'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_date',
            field=models.DateTimeField(null=True, verbose_name='資産更新日付'),
        ),
    ]
