# Generated by Django 3.2 on 2021-06-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0003_auto_20210619_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='stop_date',
            field=models.DateTimeField(null=True, verbose_name='運用停止日付'),
        ),
    ]
