# Generated by Django 3.2 on 2021-07-25 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0007_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='日時'),
        ),
        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.CharField(default='', max_length=10, verbose_name='ユーザID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='フォーマットが不正です。', regex='^[0-9a-zA-Z]+$')], verbose_name='ユーザID'),
        ),
    ]
