# Generated by Django 3.2 on 2021-07-25 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0008_auto_20210725_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='share_ratio',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='配当比率'),
        ),
    ]
