# Generated by Django 3.2 on 2021-04-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unnamed1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unnamed2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unnamed3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unnamed4',
        ),
    ]
