# Generated by Django 3.2 on 2021-04-19 04:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0002_auto_20210418_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='btc_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=34, validators=[django.core.validators.RegexValidator(message='フォーマットが不正です。', regex='^[0-9a-zA-Z]+$')], verbose_name='ビットコインアドレス'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='会員ランク'),
            preserve_default=False,
        ),
    ]
