# Generated by Django 3.2 on 2021-04-19 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0003_auto_20210419_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='btc_address',
            field=models.CharField(default='', max_length=34, validators=[django.core.validators.RegexValidator(message='フォーマットが不正です。', regex='^[0-9a-zA-Z]+$')], verbose_name='ビットコインアドレス'),
        ),
    ]
