# Generated by Django 3.2 on 2021-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0004_alter_user_btc_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[(1, 'ランク1'), (2, 'ランク2'), (3, 'ランク3'), (4, 'ランク4'), (5, 'ランク5')], max_length=2, verbose_name='会員ランク'),
        ),
    ]
