# Generated by Django 3.2 on 2021-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0006_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(1, 'ランク1'), (2, 'ランク2'), (3, 'ランク3'), (4, 'ランク4'), (5, 'ランク5')], default=0, null=True, verbose_name='会員ランク'),
        ),
    ]
