# Generated by Django 3.2 on 2021-05-19 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0009_auto_20210504_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, verbose_name='ユーザID')),
                ('date', models.DateTimeField(null=True, verbose_name='日時')),
                ('family_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('value', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1e-08)], verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(1, '運営'), (2, '特別会員'), (3, '一般会員')], default=0, null=True, verbose_name='会員ランク'),
        ),
    ]
