# Generated by Django 3.2 on 2021-06-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0011_auto_20210519_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='状況'),
        ),
    ]
