# Generated by Django 3.2 on 2021-06-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0013_alter_withdrawal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='status_date',
            field=models.DateTimeField(null=True, verbose_name='変更日時'),
        ),
    ]
