# Generated by Django 3.2 on 2021-06-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0014_withdrawal_status_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='Investment',
        ),
        migrations.AddField(
            model_name='user',
            name='asset',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=100, null=True, verbose_name='資産'),
        ),
    ]
