# Generated by Django 3.2 on 2021-06-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0015_auto_20210606_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
