# Generated by Django 3.2 on 2021-06-07 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKsystemApp', '0016_delete_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name=''),
        ),
    ]
